from pymonocle._monocle import mncl


# Data types

DATA_NULL = mncl.MNCL_DATA_NULL
DATA_BOOLEAN = mncl.MNCL_DATA_BOOLEAN
DATA_NUMBER = mncl.MNCL_DATA_NUMBER
DATA_STRING = mncl.MNCL_DATA_STRING
DATA_ARRAY = mncl.MNCL_DATA_ARRAY
DATA_OBJECT = mncl.MNCL_DATA_OBJECT


# Event types

EVENT_QUIT = mncl.MNCL_EVENT_QUIT
EVENT_INIT = mncl.MNCL_EVENT_INIT
EVENT_PREINPUT = mncl.MNCL_EVENT_PREINPUT
EVENT_KEYDOWN = mncl.MNCL_EVENT_KEYDOWN
EVENT_KEYUP = mncl.MNCL_EVENT_KEYUP
EVENT_MOUSEMOVE = mncl.MNCL_EVENT_MOUSEMOVE
EVENT_MOUSEBUTTONDOWN = mncl.MNCL_EVENT_MOUSEBUTTONDOWN
EVENT_MOUSEBUTTONUP = mncl.MNCL_EVENT_MOUSEBUTTONUP
EVENT_JOYAXISMOVE = mncl.MNCL_EVENT_JOYAXISMOVE
EVENT_JOYBUTTONDOWN = mncl.MNCL_EVENT_JOYBUTTONDOWN
EVENT_JOYBUTTONUP = mncl.MNCL_EVENT_JOYBUTTONUP
EVENT_JOYHATMOVE = mncl.MNCL_EVENT_JOYHATMOVE
EVENT_PREPHYSICS = mncl.MNCL_EVENT_PREPHYSICS
EVENT_COLLISION = mncl.MNCL_EVENT_COLLISION
EVENT_PRERENDER = mncl.MNCL_EVENT_PRERENDER
EVENT_RENDER = mncl.MNCL_EVENT_RENDER
EVENT_POSTRENDER = mncl.MNCL_EVENT_POSTRENDER
NUM_EVENTS = mncl.MNCL_NUM_EVENTS


class Keycodes(object):
    def __getattr__(self, value):
        return getattr(mncl, 'SDLK_' + value)


keycodes = Keycodes()
